export const tags = [
    "ahegao",
    "anal",
    "bdsm",
    "big boobs",
    "blow job",
    "bondage",
    "paizuri",
    "Censored",
    "comedy",
    "cosplay",
    "creampie",
    "facial",
    "loli",
    "fantasy",
    "filmed",
    "foot job",
    "futanari",
    "gangbang",
    "glasses",
    "hand job",
    "harem",
    "horror",
    "incest",
    "hd",
    "inflantion",
    "lactation",
    "maid",
    "masturbation",
    "milf",
    "mind break",
    "mind control",
    "monster",
    "nekomimi",
    "netorare",
    "nurse",
    "orgy",
    "plot",
    "pov",
    "public sex",
    "rape",
    "reverse trap",
    "rim job",
    "scat",
    "school girl",
    "shotacon",
    "softcore",
    "swimsuit",
    "teacher",
    "tentacle",
    "threesome",
    "toys",
    "trap",
    "tsundere",
    "ugly bastard",
    "Uncensored",
    "vanilla",
    "virgin",
    "watersports",
    "x-ray",
    "yuri"
]
